### ISSUE TITLE
Fatal error: Call to undefined method PEAR::_Archive_Tar()

### ISSUE THREAD

**Issue by subdesign** [tatewake/dokuwiki-plugin-backup#29]
I get following error on PHP 7.0: 
`Fatal error: Call to undefined method PEAR::_Archive_Tar() in /usr/local/share/pear70/PEAR.php on line 218`

**Comment by dsp77** [comment]
This seems to be an installation issue of your php. Can you verify, that the PEAR module is installed?

**Comment by polyfeux** [comment]
@subdesign are you by chance using All-Inkl.com as your hoster?
Because I'm using All-Inkl.com for hosting and I'm getting this message even on fresh install of DokWiki.

And it is not relevant if PHP5.5, PHP5.6 or PHP7.0 as I'm getting this error always since about two years (while using DokuWiki and this easy-to-use Backup-Plugin a quite longer).

**Comment by tatewake** [comment]
I believe this is fixed as of PR #32 (that has been merged) so I'm going to close this issue.
Please try the latest version (with the latest DokuWiki) and see if this resolves your problem.

**Comment by polyfeux** [comment]
Awesome!
It works flawlessly (backup & restore of backup) - thank you for your initiative @splitbrain & @tatewake !
