### ISSUE TITLE
Is there a completion message?  -None noted in the manual.

### ISSUE THREAD

**Issue by rgleason** [tatewake/dokuwiki-plugin-backup#30]
I have tried several backups:
Everything checked - with "Unfiltered" type backup.
Old page Revisions unchecked  with "Filtered" type backup.

Both saved about 3.2gb before the size stopped going up, There is a blank wiki page and no message appears, I waited a long time.

Is there a message and the plugin did not complete properly?
Or is there no message, and we are to just wait forever?
More messages or indication of plugin activity or status is needed!!

"Backing up, saving to "name of the file" - blinking regularly.
"Backup Failed" at the end
"Backup Completed Properly" at the end

**Comment by dsp77** [comment]
3.2GB is a lot of data. Can you verify what files are in the created tar?

Do you haven an overview how big your wiki content is?

I had an discussion on #27 and @lolo888 commented, that there is a php timeout. After that time the packaging process will end. Unfortunately it seems like the plugin does not catch that timeout. So an issue with the plugin is, that the tar-process might timeout because of too much data to package, but the plugin does not catch that and does not report its ending.

Though you should be able to see the created tar-file when you go back to the backup page where it lists existing backups.

Try: GNU Tar (filtered) with only the "pages" option checked. All other options unchecked. That should give you the smallest size of backup and hopefully not run into the timeout. Does that work?

**Comment by tatewake** [comment]
I believe this is fixed as of PR #32 (that has been merged) so I'm going to close this issue.
Please try the latest version (with the latest DokuWiki) and see if this resolves your problem.
