### ISSUE TITLE
Delete old backup in media_attic

### ISSUE THREAD

**Issue by webafrancois** [tatewake/dokuwiki-plugin-backup#38]
When I run a backup, I can download the archive and also delete the backup with the media manager in wiki:backup
But all backup are also stored in data/media_attic/wiki/backup/
How can I change this behaviour and remove this archive too ?

Thanks.

**Comment by tatewake** [comment]
Hi @webafrancois ,

DokuWiki by default stores all "media files" created inside of the `media_attic`; you can disable this behavior via [the `mediarevisions` flag](https://www.dokuwiki.org/config:mediarevisions) in the "Configuration Settings" for DokuWiki.

There does not appear to be a way to tell DokuWiki not to automatically backup specific files to `media_attic`; it's probably better for DokuWiki to change this behavior rather than my plugin delete files.

So, for the time being, I would disable `mediarevisions`, and report an issue on [DokuWiki's github issues](https://github.com/splitbrain/dokuwiki/issues) to not copy files from `wiki:backup` into `media_attic`.

Thank you.

**Comment by tatewake** [comment]
Hi @webafrancois ,

I've since spoken with the author of DokuWiki trying to track down this issue.

After our discussion, I've decided that I will add support for deleting the backups from `media_attic` in a future release.

Thank you for pointing out this issue, and I hope to have a new version in the next few weeks.

**Comment by webafrancois** [comment]
Thanks a lot.

**Comment by tatewake** [comment]
Hello @webafrancois ; this issue has been resolved as of the latest release.
You can update the BackupTool plugin from within the extension manager to see the result.

Backups in the `media_attic` directory will be automatically deleted when you run your next backup.

Best regards,
--Terence
