### ISSUE TITLE
Add an admin interface to restore a backup

### ISSUE THREAD

**Issue by 3615pipou** [tatewake/dokuwiki-plugin-backup#42]
Could it be possible to add an admin interface to restore a backup ? Sometime we don't have access to the file system.

**Comment by tatewake** [comment]
Hi @3615pipou ,

It's a good idea, but the process for restoring a backup can be more error-prone when trying to do it automatically.

In particular, the plugin would have problems if for some reason you couldn't delete, create, or overwrite a file or directory for some reason (either due to misconfigured permissions, or to a "disk full" or "disk error" situation.)

Also, because users can make "partial backups" instead of "full backups", the plugin would also need some complex logic to ensure that some directories need to have their entire file structure deleted before a restoration happens.

So for now, I have no plans to support a restoration interface.
